// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class ChatwindowTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void chatwindow() {
    driver.Navigate().GoToUrl("https://www.webhallen.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(1936, 1056);
    driver.FindElement(By.CssSelector("p:nth-child(1)")).Click();
    var elements = driver.FindElements(By.CssSelector(".content-footer > button"));
    Assert.True(elements.Count > 0);
    var elements1 = driver.FindElements(By.CssSelector(".content > div:nth-child(3)"));
    Assert.True(elements1.Count > 0);


   driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(5);
   driver.Manage().Cookies.DeleteAllCookies();
    }
}
