// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class PlaceandremoveiteminshoppingcartTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void placeandremoveiteminshoppingcart() {
    driver.Navigate().GoToUrl("https://www.webhallen.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(1936, 1056);
    driver.FindElement(By.CssSelector(".input-group > .form-control")).Click();
    driver.FindElement(By.CssSelector(".input-group > .form-control")).SendKeys("317284");
    driver.FindElement(By.CssSelector(".input-group > .form-control")).SendKeys(Keys.Enter);
    driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(10);
    driver.FindElement(By.LinkText("Myriwell 3D-Print Penna för 1.75mm Filament med LCD - Blå")).Click();
    driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(5);
    driver.FindElement(By.CssSelector(".d-block:nth-child(3)")).Click();
    driver.FindElement(By.CssSelector(".stretch-y:nth-child(1)")).Click();
    Assert.That(driver.FindElement(By.LinkText("Myriwell 3D-Print Penna för 1.75mm Filament med LCD - Blå")).Text, Is.EqualTo("Myriwell 3D-Print Penna för 1.75mm Filament med LCD - Blå"));
    driver.FindElement(By.CssSelector(".btn-default > .glyphicon")).Click();
    var elements = driver.FindElements(By.CssSelector(".level-two-heading"));
    Assert.True(elements.Count > 0);
    driver.FindElement(By.CssSelector(".glyphicon-remove")).Click();


   driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(5);
   driver.Manage().Cookies.DeleteAllCookies();
    }
}
