// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class PlaceandremoveiteminshoppingcartTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void placeandremoveiteminshoppingcart() {
    driver.Navigate().GoToUrl("https://www.webhallen.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(1936, 1056);
    driver.FindElement(By.CssSelector(".text-btn:nth-child(1) > span")).Click();
    driver.FindElement(By.CssSelector(".form-control")).Click();
    driver.FindElement(By.CssSelector(".form-control")).SendKeys("276641");
    driver.FindElement(By.CssSelector(".form-control")).SendKeys(Keys.Enter);
    driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(5);
    driver.FindElement(By.LinkText("Mysterium (Nordic)")).Click();
    driver.FindElement(By.XPath("/html/body/div[2]/div[2]/div[1]/div[3]/main/div/div[4]/div[1]/div/div[2]/div[1]/div/article/div/div[1]/div/section[2]/div[1]/button")).Click();
    driver.FindElement(By.XPath("/html/body/div[2]/div[2]/div[1]/div[2]/div/header/div/div/div[4]/div/div/label/div")).Click();
    var elements = driver.FindElements(By.CssSelector(".compact-product-image .ximg-content"));
    Assert.True(elements.Count > 0);
    driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(5);
    driver.FindElement(By.CssSelector(".btn-remove-item > .icon")).Click();
    var elements1 = driver.FindElements(By.CssSelector(".level-two-heading"));
    Assert.True(elements1.Count > 0);
    driver.FindElement(By.CssSelector(".glyphicon-remove")).Click();

    driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(5);
    driver.Manage().Cookies.DeleteAllCookies();
    }
}
