// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class Test1Artikelnr323640SviveGeminiGamingstolMrkgrTest
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }
    [Test]
    public void test1Artikelnr323640SviveGeminiGamingstolMrkgr()
    {
        driver.Navigate().GoToUrl("https://www.webhallen.com/");
        driver.Manage().Window.Size = new System.Drawing.Size(1936, 1056);
        driver.FindElement(By.CssSelector(".input-group > .form-control")).Click();
        driver.FindElement(By.CssSelector(".input-group > .form-control")).SendKeys("323640");
        driver.FindElement(By.CssSelector(".glyphicon")).Click();
        driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(10);
        driver.FindElement(By.CssSelector(".col-md-4 > .panel-thin .ximg")).Click();
        Assert.That(driver.FindElement(By.CssSelector("h1")).Text, Is.EqualTo("Svive Gemini Gamingstol - Mörkgrå"));
        Assert.That(driver.FindElement(By.CssSelector(".px-5 > p:nth-child(3)")).Text, Is.EqualTo("Artikelnr: 323640"));
    }
}

//test made by proudpond