// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class VerifyloginiconsWhenloginfieldsareemptyloginshouldfailTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void verifyloginiconsWhenloginfieldsareemptyloginshouldfail() {
    driver.Navigate().GoToUrl("https://www.webhallen.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(1920, 1040);
    driver.FindElement(By.CssSelector("strong")).Click();
    var elements = driver.FindElements(By.XPath("//header[@id=\'main-header\']/div/div/div[3]/div/div[3]/div/form/div/div/div/input"));
    Assert.True(elements.Count > 0);
    var elements1 = driver.FindElements(By.XPath("//header[@id=\'main-header\']/div/div/div[3]/div/div[3]/div/form/div/div/div[2]/input"));
    Assert.True(elements1.Count > 0);
    var elements2 = driver.FindElements(By.XPath("//header[@id=\'main-header\']/div/div/div[3]/div/div[3]/div/form/div/button"));
    Assert.True(elements2.Count > 0);
    driver.FindElement(By.XPath("//header[@id=\'main-header\']/div/div/div[3]/div/div[3]/div/form/div/button")).Click();
    {
      var elements3 = driver.FindElements(By.XPath("//header[@id=\'main-header\']/div/div/div[3]/div/div[3]/div/form/div/div[2]"));
      Assert.True(elements3.Count == 0);
    }
  }
}
