// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class Verifyitem333044shippingetcTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
       driver.Quit();
  }
  [Test]
  public void verifyitem333044shippingetc() {
    driver.Navigate().GoToUrl("https://www.webhallen.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(1920, 1040);
    driver.FindElement(By.CssSelector(".input-group > .form-control")).Click();
    driver.FindElement(By.CssSelector(".input-group > .form-control")).SendKeys("333044");
    driver.FindElement(By.CssSelector(".input-group > .form-control")).SendKeys(Keys.Enter);
    driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(10);
    driver.FindElement(By.LinkText("Xiaomi Mi Body Composition Scale 2")).Click();
    Assert.That(driver.FindElement(By.CssSelector("h1")).Text, Is.EqualTo("Xiaomi Mi Body Composition Scale 2"));
    Assert.That(driver.FindElement(By.CssSelector(".px-5 > p:nth-child(3)")).Text, Is.EqualTo("Artikelnr: 333044"));
    var elements = driver.FindElements(By.CssSelector(".ap-fill .ximg-content"));
    Assert.True(elements.Count > 0);
    driver.FindElement(By.CssSelector(".d-block:nth-child(3)")).Click();
    driver.FindElement(By.CssSelector(".stretch-y:nth-child(1)")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".free-shipping-wrap > span")).Text, Is.Not.EqualTo("Should not be free shipping"));
    driver.Manage().Cookies.DeleteAllCookies();
    driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(10);
    }
}
