// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class VerifieraheaderTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void verifieraheader() {
    driver.Navigate().GoToUrl("https://www.webhallen.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(1936, 1056);
    var elements = driver.FindElements(By.CssSelector(".logo-link .ximg-content"));
    Assert.True(elements.Count > 0);
    var elements1 = driver.FindElements(By.CssSelector(".input-group > .form-control"));
    Assert.True(elements1.Count > 0);
    var elements2 = driver.FindElements(By.CssSelector(".d-flex .icon-button"));
    Assert.True(elements2.Count > 0);
    var elements3 = driver.FindElements(By.CssSelector("strong"));
    Assert.True(elements3.Count > 0);
    var elements4 = driver.FindElements(By.LinkText("Skapa konto"));
    Assert.True(elements4.Count > 0);
    var elements5 = driver.FindElements(By.CssSelector(".cart-header"));
    Assert.True(elements5.Count > 0);
  }
}
